### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by keithsimkin** [Flutterwave/Woocommerce#21]
domain.com?/pay_for_item=rave&jobid=132&amount=1&extras=&extras_amounts=&pck_price_val=

that is all I get with a blank screen what should be the error

**Comment by bajoski34** [comment]
Hi @keithsimkin please can you be more specific

**Comment by faithoyebode** [comment]
I think what @keithsimkin means by plugin not working is that, the settings page of woocommerce goes blank on the wordpress dashboard when you try to access it after activating the plugin
![image](https://user-images.githubusercontent.com/47439363/127856090-57e5d6db-a92a-4d45-8a00-5547b642b2e0.png)

**Comment by bajoski34** [comment]
Hi @faithoyebode please kindly follow the setup instructions here. https://support.flutterwave.com/en/articles/3632754-how-to-integrate-flutterwave-into-woocommerce 

Note: please make sure you have the required plugins installed before using the plugin. 

kind regards

**Comment by keithsimkin** [comment]
> Hi @keithsimkin please can you be more specific

well thank you for the respond but I ended up building my own plugin

**Comment by 233developers** [comment]
@keithsimkin Can you share the plugin you built? Thank you
@faithoyebode Has Flutterwave fixed the issue? I have seen it even on WordPress Plugin side that it's got this issue... Kindly fix it if it's not... I want to use it

**Comment by bajoski34** [comment]
Hi @233developers please use the new plugin here. https://github.com/Flutterwave/Flutterwave-WooCommerce

**Comment by keithsimkin** [comment]
> @keithsimkin Can you share the plugin you built? Thank you @faithoyebode Has Flutterwave fixed the issue? I have seen it even on the WordPress Plugin side that it's got this issue... Kindly fix it if it's not... I want to use it

**Comment by keithsimkin** [comment]
@233developers do you still need help

**Comment by bajoski34** [comment]
Hi @keithsimkin hope your issue has been resolved now

**Comment by Corvus97** [comment]
Hello @keithsimkin @233developers 👋🏾,

Thank you for sharing this feedback with the DX team. We value your input and work on every comment you share here.

We have fixed the reported behaviour in the latest version of the plugin and made additional updates to improve your experience with the plugin.

Please check out the update and share your experience with the latest version via [email](mailto:developers@flutterwavego.com)

Join our [Slack community](https://bit.ly/34Vkzcg) to get updates on our plugins, APIs and events.

Cheers guys!😊
Cornelius
