### ISSUE TITLE
Unable to validate account/mobile money account invalid even though number is correct. 

### ISSUE THREAD

**Issue by hadrongh** [Flutterwave/WooCommerce#5]
On a desktop pc, it says transaction failed due to insufficient balance even though there's enough money in the account. On mobile website, it says validate account/mobile money account invalid.

**Comment by corneliusyaovi** [comment]
Hello @hadrongh,

Thank you for sharing this with the team. This error is typically returned when your account is not enabled for mobile money.

Kindly send us an email at developers@flutterwavego.com requesting this feature on your account.
